language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: MINIMUM_VERSIONS=false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - if [[ $MINIMUM_VERSIONS = false ]]; then composer install; fi
  - if [[ $MINIMUM_VERSIONS = true ]]; then composer update --no-interaction --prefer-lowest; fi

jobs:
  include:
    - stage: style check
      script: composer run style:check
    - stage: tests
      script: composer run test
